// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/tarxzfv/go-deepl/internal/pkg/http"
	"github.com/tarxzfv/go-deepl/internal/pkg/translation"
	"github.com/tarxzfv/go-deepl/pkg/deepl"
)

// Injectors from wire.go:

func InitializeTranslator(config *deepl.Config) (translation.Translator, error) {
	client := http.NewDefaultHTTPClient()
	clientV2, err := deepl.NewDeepLClient(config, client)
	if err != nil {
		return nil, err
	}
	translator := translation.NewTranslator(clientV2)
	return translator, nil
}
